services:
  defi-db:
    image: postgres:15.1
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - ./.data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

  test-db:
    image: postgres:15.1
    ports:
      - ${DATABASE_TEST_PORT}:5432
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

  defi-ad:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  defi-rd:
    image: redis:7-alpine
    ports:
      - ${REDIS_PORT}:6379
    environment:
      REDIS_USER: ${REDIS_USERNAME}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
